

[tasks."build:module"]
script = '''
sui move build
'''

[tasks."test:module"]
script = '''
sui move test
'''

[tasks."deploy:devnet"]
dependencies = [
  "build:module", # "test:module",
]
script = '''
sui client publish --path build/coin_list --gas-budget 30000
'''

[tasks."alice:transfer"]
script = '''
sui client call \
  --function transfer \
  --module sui \
  --package 0x2 \
  --args \
    0x471c8e241d0473c34753461529b70f9c4ed3151b \
    0x3cbf06e9997b3864e3baad6bc0f0ef8ec423cd75 \
  --gas-budget 1000
'''

# --package 0xb48107fcb0235df7f3f983266e2daa0fccfe22fe \
# --module coin_list \
# --function init_devnet_BTC \
[tasks."alice:mint:BTC"]
script = '''
sui client call \
  --package 0xda4607878cebdbe5c818dbf1b4be2c54467091b5 \
  --module devnet_btc \
  --function mint \
  --args \
    0x02514d2a7aaf75372e14d37cb487dc1b482239eb \
    100 \
  --gas-budget 1000
'''

[tasks."alice:faucet:BTC"]
script = '''
sui client call \
  --package 0x392c4b2f7c710cb1f4f9cd0b7747ef8ba124fb53 \
  --module coin_list \
  --function init_devnet_BTC \
  --gas-budget 1000
'''
